# Generated by Django 5.2.10 on 2026-03-17 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BankApp', '0004_remove_investmentplan_interest_rate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinvestment',
            options={'ordering': ['-created_at'], 'verbose_name': 'User Investment', 'verbose_name_plural': 'User Investments'},
        ),
    ]
